/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package edu.stanford.photoSpreadParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int SPECIAL_CONST = 5;
  /** RegularExpression Id. */
  int NULL = 6;
  /** RegularExpression Id. */
  int LBRACE = 7;
  /** RegularExpression Id. */
  int RBRACE = 8;
  /** RegularExpression Id. */
  int LBRACKET = 9;
  /** RegularExpression Id. */
  int RBRACKET = 10;
  /** RegularExpression Id. */
  int LPARENS = 11;
  /** RegularExpression Id. */
  int RPARENS = 12;
  /** RegularExpression Id. */
  int COMMA = 13;
  /** RegularExpression Id. */
  int AND = 14;
  /** RegularExpression Id. */
  int OR = 15;
  /** RegularExpression Id. */
  int DOLLAR = 16;
  /** RegularExpression Id. */
  int NE = 17;
  /** RegularExpression Id. */
  int LEQ = 18;
  /** RegularExpression Id. */
  int GEQ = 19;
  /** RegularExpression Id. */
  int EQ = 20;
  /** RegularExpression Id. */
  int LT = 21;
  /** RegularExpression Id. */
  int GT = 22;
  /** RegularExpression Id. */
  int PERIOD = 23;
  /** RegularExpression Id. */
  int DOUBLE_QUOTE = 24;
  /** RegularExpression Id. */
  int SINGLE_QUOTE = 25;
  /** RegularExpression Id. */
  int UNION = 26;
  /** RegularExpression Id. */
  int SUM = 27;
  /** RegularExpression Id. */
  int MIN = 28;
  /** RegularExpression Id. */
  int MAX = 29;
  /** RegularExpression Id. */
  int COUNT = 30;
  /** RegularExpression Id. */
  int AVG = 31;
  /** RegularExpression Id. */
  int NUMBER = 32;
  /** RegularExpression Id. */
  int SIGNED_NUMBER = 33;
  /** RegularExpression Id. */
  int DIGIT = 34;
  /** RegularExpression Id. */
  int DIGITS = 35;
  /** RegularExpression Id. */
  int CHAR_UPPER = 36;
  /** RegularExpression Id. */
  int CHAR_LOWER = 37;
  /** RegularExpression Id. */
  int CHAR = 38;
  /** RegularExpression Id. */
  int CHARS_UPPER = 39;
  /** RegularExpression Id. */
  int IDENTIFIER = 40;
  /** RegularExpression Id. */
  int VAR_NAME = 41;
  /** RegularExpression Id. */
  int CHARS = 42;
  /** RegularExpression Id. */
  int CHAR_ALPHA = 43;
  /** RegularExpression Id. */
  int MIXED_CHAR = 44;
  /** RegularExpression Id. */
  int MIXED_CHARS = 45;
  /** RegularExpression Id. */
  int ALPHA_NUMERIC_CHARS = 46;
  /** RegularExpression Id. */
  int STRING_CONSTANT = 47;
  /** RegularExpression Id. */
  int TO_DEFAULT = 48;
  /** RegularExpression Id. */
  int OBJ_COLLECTION = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SPECIAL_CONST = 1;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"_/\"",
    "\"null\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\"&\"",
    "\"|\"",
    "\"$\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\".\"",
    "\"\\\"\"",
    "\"\\\'\"",
    "\"union\"",
    "\"sum\"",
    "\"min\"",
    "\"max\"",
    "\"count\"",
    "\"avg\"",
    "<NUMBER>",
    "<SIGNED_NUMBER>",
    "<DIGIT>",
    "<DIGITS>",
    "<CHAR_UPPER>",
    "<CHAR_LOWER>",
    "<CHAR>",
    "<CHARS_UPPER>",
    "<IDENTIFIER>",
    "<VAR_NAME>",
    "<CHARS>",
    "<CHAR_ALPHA>",
    "<MIXED_CHAR>",
    "<MIXED_CHARS>",
    "<ALPHA_NUMERIC_CHARS>",
    "<STRING_CONSTANT>",
    "\"/_\"",
    "\"Objects\"",
    "\":\"",
  };

}
