/* Generated By:JavaCC: Do not edit this line. ExpressionParserConstants.java */
package photoSpreadParser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int LBRACE = 5;
  /** RegularExpression Id. */
  int RBRACE = 6;
  /** RegularExpression Id. */
  int LPARENS = 7;
  /** RegularExpression Id. */
  int RPARENS = 8;
  /** RegularExpression Id. */
  int EQ = 9;
  /** RegularExpression Id. */
  int LT = 10;
  /** RegularExpression Id. */
  int GT = 11;
  /** RegularExpression Id. */
  int NE = 12;
  /** RegularExpression Id. */
  int LEQ = 13;
  /** RegularExpression Id. */
  int GEQ = 14;
  /** RegularExpression Id. */
  int UNION = 15;
  /** RegularExpression Id. */
  int COLNAME = 16;
  /** RegularExpression Id. */
  int ROWID = 17;
  /** RegularExpression Id. */
  int NUMBER = 18;
  /** RegularExpression Id. */
  int DIGITS = 19;
  /** RegularExpression Id. */
  int CHARS = 20;
  /** RegularExpression Id. */
  int LOWER_CHARS = 21;
  /** RegularExpression Id. */
  int UPPER_CHARS = 22;
  /** RegularExpression Id. */
  int CELLCOLUMN = 23;
  /** RegularExpression Id. */
  int CELLRANGE = 24;
  /** RegularExpression Id. */
  int CONDITION = 25;
  /** RegularExpression Id. */
  int COMP_OP = 26;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"=\"",
    "\"<\"",
    "\">\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"union\"",
    "<COLNAME>",
    "<ROWID>",
    "<NUMBER>",
    "<DIGITS>",
    "<CHARS>",
    "<LOWER_CHARS>",
    "<UPPER_CHARS>",
    "<CELLCOLUMN>",
    "<CELLRANGE>",
    "<CONDITION>",
    "<COMP_OP>",
    "\",\"",
    "\":\"",
  };

}
